---
- hosts: all
  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Install cron as requisite
      package:
        name: cron
        state: present
      become: true
